// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AESDecrypt(arg1) {
  return window['go']['main']['App']['AESDecrypt'](arg1);
}

export function AESEncrypt(arg1) {
  return window['go']['main']['App']['AESEncrypt'](arg1);
}

export function AigisKeyGen(arg1) {
  return window['go']['main']['App']['AigisKeyGen'](arg1);
}

export function AigisSign(arg1) {
  return window['go']['main']['App']['AigisSign'](arg1);
}

export function AigisVerify(arg1) {
  return window['go']['main']['App']['AigisVerify'](arg1);
}

export function Base32Decode(arg1) {
  return window['go']['main']['App']['Base32Decode'](arg1);
}

export function Base32Encode(arg1) {
  return window['go']['main']['App']['Base32Encode'](arg1);
}

export function Base58Decode(arg1) {
  return window['go']['main']['App']['Base58Decode'](arg1);
}

export function Base58Encode(arg1) {
  return window['go']['main']['App']['Base58Encode'](arg1);
}

export function Base64Decode(arg1) {
  return window['go']['main']['App']['Base64Decode'](arg1);
}

export function Base64Encode(arg1) {
  return window['go']['main']['App']['Base64Encode'](arg1);
}

export function BaseConvert(arg1) {
  return window['go']['main']['App']['BaseConvert'](arg1);
}

export function Bech32Decode(arg1) {
  return window['go']['main']['App']['Bech32Decode'](arg1);
}

export function Bech32Encode(arg1) {
  return window['go']['main']['App']['Bech32Encode'](arg1);
}

export function BigIntOperation(arg1) {
  return window['go']['main']['App']['BigIntOperation'](arg1);
}

export function ChaCha20Decrypt(arg1) {
  return window['go']['main']['App']['ChaCha20Decrypt'](arg1);
}

export function ChaCha20Encrypt(arg1) {
  return window['go']['main']['App']['ChaCha20Encrypt'](arg1);
}

export function ComputeARQC(arg1) {
  return window['go']['main']['App']['ComputeARQC'](arg1);
}

export function ComputeCVV(arg1) {
  return window['go']['main']['App']['ComputeCVV'](arg1);
}

export function ComputeMAC(arg1) {
  return window['go']['main']['App']['ComputeMAC'](arg1);
}

export function ComputePVV(arg1) {
  return window['go']['main']['App']['ComputePVV'](arg1);
}

export function ConvertKey(arg1) {
  return window['go']['main']['App']['ConvertKey'](arg1);
}

export function DESDecrypt(arg1) {
  return window['go']['main']['App']['DESDecrypt'](arg1);
}

export function DESEncrypt(arg1) {
  return window['go']['main']['App']['DESEncrypt'](arg1);
}

export function DecryptFile(arg1) {
  return window['go']['main']['App']['DecryptFile'](arg1);
}

export function DecryptPINBlock(arg1) {
  return window['go']['main']['App']['DecryptPINBlock'](arg1);
}

export function DeriveEMVUDK(arg1) {
  return window['go']['main']['App']['DeriveEMVUDK'](arg1);
}

export function DeriveKey(arg1) {
  return window['go']['main']['App']['DeriveKey'](arg1);
}

export function DeriveSM4UDK(arg1) {
  return window['go']['main']['App']['DeriveSM4UDK'](arg1);
}

export function DoubleOneWay(arg1) {
  return window['go']['main']['App']['DoubleOneWay'](arg1);
}

export function ECCGenerateKey(arg1) {
  return window['go']['main']['App']['ECCGenerateKey'](arg1);
}

export function ECCSign(arg1) {
  return window['go']['main']['App']['ECCSign'](arg1);
}

export function ECCVerify(arg1) {
  return window['go']['main']['App']['ECCVerify'](arg1);
}

export function ECDHCompute(arg1) {
  return window['go']['main']['App']['ECDHCompute'](arg1);
}

export function Ed25519KeyGen() {
  return window['go']['main']['App']['Ed25519KeyGen']();
}

export function Ed25519Sign(arg1) {
  return window['go']['main']['App']['Ed25519Sign'](arg1);
}

export function Ed25519Verify(arg1) {
  return window['go']['main']['App']['Ed25519Verify'](arg1);
}

export function Ed448KeyGen() {
  return window['go']['main']['App']['Ed448KeyGen']();
}

export function Ed448Sign(arg1) {
  return window['go']['main']['App']['Ed448Sign'](arg1);
}

export function Ed448Verify(arg1) {
  return window['go']['main']['App']['Ed448Verify'](arg1);
}

export function EncryptFile(arg1) {
  return window['go']['main']['App']['EncryptFile'](arg1);
}

export function EncryptPINBlock(arg1) {
  return window['go']['main']['App']['EncryptPINBlock'](arg1);
}

export function FPEDecrypt(arg1) {
  return window['go']['main']['App']['FPEDecrypt'](arg1);
}

export function FPEEncrypt(arg1) {
  return window['go']['main']['App']['FPEEncrypt'](arg1);
}

export function FalconKeyGen(arg1) {
  return window['go']['main']['App']['FalconKeyGen'](arg1);
}

export function FalconSign(arg1) {
  return window['go']['main']['App']['FalconSign'](arg1);
}

export function FalconVerify(arg1) {
  return window['go']['main']['App']['FalconVerify'](arg1);
}

export function FormatJSON(arg1) {
  return window['go']['main']['App']['FormatJSON'](arg1);
}

export function GenerateCSR(arg1) {
  return window['go']['main']['App']['GenerateCSR'](arg1);
}

export function GenerateCertificate(arg1) {
  return window['go']['main']['App']['GenerateCertificate'](arg1);
}

export function GenerateDualCertificates(arg1) {
  return window['go']['main']['App']['GenerateDualCertificates'](arg1);
}

export function GenerateInternalSignedCert(arg1) {
  return window['go']['main']['App']['GenerateInternalSignedCert'](arg1);
}

export function GeneratePINBlock(arg1) {
  return window['go']['main']['App']['GeneratePINBlock'](arg1);
}

export function GenerateRandom(arg1) {
  return window['go']['main']['App']['GenerateRandom'](arg1);
}

export function GenerateSelfSignedCert(arg1) {
  return window['go']['main']['App']['GenerateSelfSignedCert'](arg1);
}

export function GetInternalRootCert(arg1) {
  return window['go']['main']['App']['GetInternalRootCert'](arg1);
}

export function HMAC(arg1) {
  return window['go']['main']['App']['HMAC'](arg1);
}

export function HQCDecapsulate(arg1) {
  return window['go']['main']['App']['HQCDecapsulate'](arg1);
}

export function HQCEncapsulate(arg1) {
  return window['go']['main']['App']['HQCEncapsulate'](arg1);
}

export function HQCKeyGen(arg1) {
  return window['go']['main']['App']['HQCKeyGen'](arg1);
}

export function Hash(arg1) {
  return window['go']['main']['App']['Hash'](arg1);
}

export function HashFile(arg1) {
  return window['go']['main']['App']['HashFile'](arg1);
}

export function HexToString(arg1) {
  return window['go']['main']['App']['HexToString'](arg1);
}

export function MLDSAKeyGen(arg1) {
  return window['go']['main']['App']['MLDSAKeyGen'](arg1);
}

export function MLDSASign(arg1) {
  return window['go']['main']['App']['MLDSASign'](arg1);
}

export function MLDSAVerify(arg1) {
  return window['go']['main']['App']['MLDSAVerify'](arg1);
}

export function MLKEMDecapsulate(arg1) {
  return window['go']['main']['App']['MLKEMDecapsulate'](arg1);
}

export function MLKEMEncapsulate(arg1) {
  return window['go']['main']['App']['MLKEMEncapsulate'](arg1);
}

export function MLKEMKeyGen(arg1) {
  return window['go']['main']['App']['MLKEMKeyGen'](arg1);
}

export function MakeGMEnvelope(arg1) {
  return window['go']['main']['App']['MakeGMEnvelope'](arg1);
}

export function OpenGMEnvelope(arg1) {
  return window['go']['main']['App']['OpenGMEnvelope'](arg1);
}

export function PaddingApply(arg1) {
  return window['go']['main']['App']['PaddingApply'](arg1);
}

export function PaddingRemove(arg1) {
  return window['go']['main']['App']['PaddingRemove'](arg1);
}

export function ParseASN1(arg1) {
  return window['go']['main']['App']['ParseASN1'](arg1);
}

export function ParseASN1File(arg1) {
  return window['go']['main']['App']['ParseASN1File'](arg1);
}

export function ParseCertificate(arg1) {
  return window['go']['main']['App']['ParseCertificate'](arg1);
}

export function ParseJWT(arg1) {
  return window['go']['main']['App']['ParseJWT'](arg1);
}

export function ParsePINBlock(arg1) {
  return window['go']['main']['App']['ParsePINBlock'](arg1);
}

export function ParsePKCS12(arg1) {
  return window['go']['main']['App']['ParsePKCS12'](arg1);
}

export function ParsePKCS12File(arg1, arg2) {
  return window['go']['main']['App']['ParsePKCS12File'](arg1, arg2);
}

export function RC4Decrypt(arg1) {
  return window['go']['main']['App']['RC4Decrypt'](arg1);
}

export function RC4Encrypt(arg1) {
  return window['go']['main']['App']['RC4Encrypt'](arg1);
}

export function RSADecrypt(arg1) {
  return window['go']['main']['App']['RSADecrypt'](arg1);
}

export function RSAEncrypt(arg1) {
  return window['go']['main']['App']['RSAEncrypt'](arg1);
}

export function RSAGenerateKey(arg1) {
  return window['go']['main']['App']['RSAGenerateKey'](arg1);
}

export function RSASign(arg1) {
  return window['go']['main']['App']['RSASign'](arg1);
}

export function RSAVerify(arg1) {
  return window['go']['main']['App']['RSAVerify'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RetailMAC(arg1) {
  return window['go']['main']['App']['RetailMAC'](arg1);
}

export function SIVDecrypt(arg1) {
  return window['go']['main']['App']['SIVDecrypt'](arg1);
}

export function SIVEncrypt(arg1) {
  return window['go']['main']['App']['SIVEncrypt'](arg1);
}

export function SLHDSAKeyGen(arg1) {
  return window['go']['main']['App']['SLHDSAKeyGen'](arg1);
}

export function SLHDSASign(arg1) {
  return window['go']['main']['App']['SLHDSASign'](arg1);
}

export function SLHDSAVerify(arg1) {
  return window['go']['main']['App']['SLHDSAVerify'](arg1);
}

export function SM2Decrypt(arg1) {
  return window['go']['main']['App']['SM2Decrypt'](arg1);
}

export function SM2DecryptPIN(arg1) {
  return window['go']['main']['App']['SM2DecryptPIN'](arg1);
}

export function SM2Encrypt(arg1) {
  return window['go']['main']['App']['SM2Encrypt'](arg1);
}

export function SM2EncryptPIN(arg1) {
  return window['go']['main']['App']['SM2EncryptPIN'](arg1);
}

export function SM2GenerateKey() {
  return window['go']['main']['App']['SM2GenerateKey']();
}

export function SM2KeyAgreement(arg1) {
  return window['go']['main']['App']['SM2KeyAgreement'](arg1);
}

export function SM2Sign(arg1) {
  return window['go']['main']['App']['SM2Sign'](arg1);
}

export function SM2Verify(arg1) {
  return window['go']['main']['App']['SM2Verify'](arg1);
}

export function SM3HMAC(arg1) {
  return window['go']['main']['App']['SM3HMAC'](arg1);
}

export function SM3Hash(arg1) {
  return window['go']['main']['App']['SM3Hash'](arg1);
}

export function SM4CMAC(arg1) {
  return window['go']['main']['App']['SM4CMAC'](arg1);
}

export function SM4Decrypt(arg1) {
  return window['go']['main']['App']['SM4Decrypt'](arg1);
}

export function SM4DecryptFinance(arg1) {
  return window['go']['main']['App']['SM4DecryptFinance'](arg1);
}

export function SM4DecryptPIN(arg1) {
  return window['go']['main']['App']['SM4DecryptPIN'](arg1);
}

export function SM4Encrypt(arg1) {
  return window['go']['main']['App']['SM4Encrypt'](arg1);
}

export function SM4EncryptFinance(arg1) {
  return window['go']['main']['App']['SM4EncryptFinance'](arg1);
}

export function SM4EncryptPIN(arg1) {
  return window['go']['main']['App']['SM4EncryptPIN'](arg1);
}

export function SM4MAC(arg1) {
  return window['go']['main']['App']['SM4MAC'](arg1);
}

export function SM9Decrypt(arg1) {
  return window['go']['main']['App']['SM9Decrypt'](arg1);
}

export function SM9Encrypt(arg1) {
  return window['go']['main']['App']['SM9Encrypt'](arg1);
}

export function SM9GenerateEncKey(arg1, arg2) {
  return window['go']['main']['App']['SM9GenerateEncKey'](arg1, arg2);
}

export function SM9GenerateMasterKey() {
  return window['go']['main']['App']['SM9GenerateMasterKey']();
}

export function SM9Sign(arg1) {
  return window['go']['main']['App']['SM9Sign'](arg1);
}

export function SM9Verify(arg1) {
  return window['go']['main']['App']['SM9Verify'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendPacket(arg1) {
  return window['go']['main']['App']['SendPacket'](arg1);
}

export function StringToHex(arg1) {
  return window['go']['main']['App']['StringToHex'](arg1);
}

export function TDESDecrypt(arg1) {
  return window['go']['main']['App']['TDESDecrypt'](arg1);
}

export function TDESEncrypt(arg1) {
  return window['go']['main']['App']['TDESEncrypt'](arg1);
}

export function TimestampConvert(arg1) {
  return window['go']['main']['App']['TimestampConvert'](arg1);
}

export function URLDecode(arg1) {
  return window['go']['main']['App']['URLDecode'](arg1);
}

export function URLEncode(arg1) {
  return window['go']['main']['App']['URLEncode'](arg1);
}

export function UnicodeDecode(arg1) {
  return window['go']['main']['App']['UnicodeDecode'](arg1);
}

export function UnicodeEncode(arg1) {
  return window['go']['main']['App']['UnicodeEncode'](arg1);
}

export function VerifyCertChain(arg1) {
  return window['go']['main']['App']['VerifyCertChain'](arg1);
}

export function X25519Exchange(arg1) {
  return window['go']['main']['App']['X25519Exchange'](arg1);
}

export function X25519KeyGen() {
  return window['go']['main']['App']['X25519KeyGen']();
}

export function XORCompute(arg1) {
  return window['go']['main']['App']['XORCompute'](arg1);
}

export function ZUCDecrypt(arg1) {
  return window['go']['main']['App']['ZUCDecrypt'](arg1);
}

export function ZUCEncrypt(arg1) {
  return window['go']['main']['App']['ZUCEncrypt'](arg1);
}
