// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {symmetric} from '../models';
import {pqc} from '../models';
import {utils} from '../models';
import {finance} from '../models';
import {mac} from '../models';
import {kdf} from '../models';
import {asymmetric} from '../models';
import {hash} from '../models';
import {gm} from '../models';

export function AESDecrypt(arg1:symmetric.AESRequest):Promise<symmetric.CryptoResult>;

export function AESEncrypt(arg1:symmetric.AESRequest):Promise<symmetric.CryptoResult>;

export function AigisKeyGen(arg1:string):Promise<pqc.PQCKeyResult>;

export function AigisSign(arg1:pqc.SLHDSARequest):Promise<symmetric.CryptoResult>;

export function AigisVerify(arg1:pqc.SLHDSAVerifyRequest):Promise<symmetric.CryptoResult>;

export function Base32Decode(arg1:utils.Base32Request):Promise<utils.ToolResult>;

export function Base32Encode(arg1:utils.Base32Request):Promise<utils.ToolResult>;

export function Base58Decode(arg1:utils.Base58Request):Promise<utils.ToolResult>;

export function Base58Encode(arg1:utils.Base58Request):Promise<utils.ToolResult>;

export function Base64Decode(arg1:utils.Base64Request):Promise<utils.ToolResult>;

export function Base64Encode(arg1:utils.Base64Request):Promise<utils.ToolResult>;

export function BaseConvert(arg1:utils.BaseConvertRequest):Promise<utils.ToolResult>;

export function Bech32Decode(arg1:string):Promise<utils.Bech32DecodeResult>;

export function Bech32Encode(arg1:utils.Bech32EncodeRequest):Promise<utils.ToolResult>;

export function BigIntOperation(arg1:utils.BigIntRequest):Promise<utils.ToolResult>;

export function ChaCha20Decrypt(arg1:symmetric.ChaChaRequest):Promise<symmetric.CryptoResult>;

export function ChaCha20Encrypt(arg1:symmetric.ChaChaRequest):Promise<symmetric.CryptoResult>;

export function ComputeARQC(arg1:finance.EMVACRequest):Promise<symmetric.CryptoResult>;

export function ComputeCVV(arg1:finance.CVVRequest):Promise<finance.CVVResult>;

export function ComputeMAC(arg1:mac.MACRequest):Promise<symmetric.CryptoResult>;

export function ComputePVV(arg1:finance.PVVRequest):Promise<finance.PVVResult>;

export function ConvertKey(arg1:utils.KeyConvertRequest):Promise<utils.KeyConvertResult>;

export function DESDecrypt(arg1:symmetric.DESRequest):Promise<symmetric.CryptoResult>;

export function DESEncrypt(arg1:symmetric.DESRequest):Promise<symmetric.CryptoResult>;

export function DecryptFile(arg1:utils.FileDecryptRequest):Promise<utils.ToolResult>;

export function DecryptPINBlock(arg1:finance.PINEncryptRequest):Promise<symmetric.CryptoResult>;

export function DeriveEMVUDK(arg1:finance.UDKRequest):Promise<finance.UDKResult>;

export function DeriveKey(arg1:kdf.KDFRequest):Promise<symmetric.CryptoResult>;

export function DeriveSM4UDK(arg1:finance.SM4UDKRequest):Promise<finance.UDKResult>;

export function DoubleOneWay(arg1:finance.DOWRequest):Promise<finance.DOWResult>;

export function ECCGenerateKey(arg1:string):Promise<asymmetric.KeyPairResult>;

export function ECCSign(arg1:asymmetric.ECCRequest):Promise<symmetric.CryptoResult>;

export function ECCVerify(arg1:asymmetric.ECCVerifyRequest):Promise<symmetric.CryptoResult>;

export function ECDHCompute(arg1:asymmetric.ECDHRequest):Promise<symmetric.CryptoResult>;

export function Ed25519KeyGen():Promise<asymmetric.KeyPairResult>;

export function Ed25519Sign(arg1:asymmetric.EdDSARequest):Promise<symmetric.CryptoResult>;

export function Ed25519Verify(arg1:asymmetric.EdDSAVerifyRequest):Promise<symmetric.CryptoResult>;

export function Ed448KeyGen():Promise<asymmetric.KeyPairResult>;

export function Ed448Sign(arg1:asymmetric.Ed448Request):Promise<symmetric.CryptoResult>;

export function Ed448Verify(arg1:asymmetric.Ed448VerifyRequest):Promise<symmetric.CryptoResult>;

export function EncryptFile(arg1:utils.FileEncryptRequest):Promise<utils.ToolResult>;

export function EncryptPINBlock(arg1:finance.PINEncryptRequest):Promise<symmetric.CryptoResult>;

export function FPEDecrypt(arg1:symmetric.FPERequest):Promise<symmetric.CryptoResult>;

export function FPEEncrypt(arg1:symmetric.FPERequest):Promise<symmetric.CryptoResult>;

export function FalconKeyGen(arg1:string):Promise<pqc.PQCKeyResult>;

export function FalconSign(arg1:pqc.SLHDSARequest):Promise<symmetric.CryptoResult>;

export function FalconVerify(arg1:pqc.SLHDSAVerifyRequest):Promise<symmetric.CryptoResult>;

export function FormatJSON(arg1:string):Promise<utils.ToolResult>;

export function GenerateCSR(arg1:utils.CSRRequest):Promise<utils.ToolResult>;

export function GenerateCertificate(arg1:utils.CertGenRequest):Promise<utils.ToolResult>;

export function GenerateDualCertificates(arg1:utils.SelfSignedCertRequest):Promise<utils.DualCertResult>;

export function GenerateInternalSignedCert(arg1:utils.SelfSignedCertRequest):Promise<utils.InternalCAResult>;

export function GeneratePINBlock(arg1:finance.PINBlockRequest):Promise<finance.PINBlockResult>;

export function GenerateRandom(arg1:utils.RandomRequest):Promise<utils.ToolResult>;

export function GenerateSelfSignedCert(arg1:utils.SelfSignedCertRequest):Promise<utils.SelfSignedCertResult>;

export function GetInternalRootCert(arg1:string):Promise<string>;

export function HMAC(arg1:hash.HMACRequest):Promise<symmetric.CryptoResult>;

export function HQCDecapsulate(arg1:pqc.MLKEMDecapRequest):Promise<symmetric.CryptoResult>;

export function HQCEncapsulate(arg1:pqc.MLKEMRequest):Promise<pqc.PQCEncapResult>;

export function HQCKeyGen(arg1:string):Promise<pqc.PQCKeyResult>;

export function Hash(arg1:hash.HashRequest):Promise<symmetric.CryptoResult>;

export function HashFile(arg1:utils.FileHashRequest):Promise<utils.ToolResult>;

export function HexToString(arg1:string):Promise<utils.ToolResult>;

export function MLDSAKeyGen(arg1:string):Promise<pqc.PQCKeyResult>;

export function MLDSASign(arg1:pqc.MLDSARequest):Promise<symmetric.CryptoResult>;

export function MLDSAVerify(arg1:pqc.MLDSAVerifyRequest):Promise<symmetric.CryptoResult>;

export function MLKEMDecapsulate(arg1:pqc.MLKEMDecapRequest):Promise<symmetric.CryptoResult>;

export function MLKEMEncapsulate(arg1:pqc.MLKEMRequest):Promise<pqc.PQCEncapResult>;

export function MLKEMKeyGen(arg1:string):Promise<pqc.PQCKeyResult>;

export function MakeGMEnvelope(arg1:gm.GMEnvelopeRequest):Promise<symmetric.CryptoResult>;

export function OpenGMEnvelope(arg1:gm.GMEnvelopeOpenRequest):Promise<symmetric.CryptoResult>;

export function PaddingApply(arg1:utils.PaddingRequest):Promise<utils.ToolResult>;

export function PaddingRemove(arg1:utils.PaddingRequest):Promise<utils.ToolResult>;

export function ParseASN1(arg1:utils.ASN1Request):Promise<utils.ToolResult>;

export function ParseASN1File(arg1:string):Promise<utils.ToolResult>;

export function ParseCertificate(arg1:string):Promise<utils.ToolResult>;

export function ParseJWT(arg1:utils.JWTRequest):Promise<utils.JWTResult>;

export function ParsePINBlock(arg1:finance.PINBlockParseRequest):Promise<finance.PINParseResult>;

export function ParsePKCS12(arg1:utils.PKCS12Request):Promise<utils.PKCS12Result>;

export function ParsePKCS12File(arg1:string,arg2:string):Promise<utils.PKCS12Result>;

export function RC4Decrypt(arg1:symmetric.RC4Request):Promise<symmetric.CryptoResult>;

export function RC4Encrypt(arg1:symmetric.RC4Request):Promise<symmetric.CryptoResult>;

export function RSADecrypt(arg1:asymmetric.RSARequest):Promise<symmetric.CryptoResult>;

export function RSAEncrypt(arg1:asymmetric.RSARequest):Promise<symmetric.CryptoResult>;

export function RSAGenerateKey(arg1:number):Promise<asymmetric.KeyPairResult>;

export function RSASign(arg1:asymmetric.RSASignRequest):Promise<symmetric.CryptoResult>;

export function RSAVerify(arg1:asymmetric.RSAVerifyRequest):Promise<symmetric.CryptoResult>;

export function ReadFile(arg1:string):Promise<string>;

export function RetailMAC(arg1:finance.RetailMACRequest):Promise<symmetric.CryptoResult>;

export function SIVDecrypt(arg1:symmetric.SIVRequest):Promise<symmetric.CryptoResult>;

export function SIVEncrypt(arg1:symmetric.SIVRequest):Promise<symmetric.CryptoResult>;

export function SLHDSAKeyGen(arg1:string):Promise<pqc.PQCKeyResult>;

export function SLHDSASign(arg1:pqc.SLHDSARequest):Promise<symmetric.CryptoResult>;

export function SLHDSAVerify(arg1:pqc.SLHDSAVerifyRequest):Promise<symmetric.CryptoResult>;

export function SM2Decrypt(arg1:gm.SM2Request):Promise<symmetric.CryptoResult>;

export function SM2DecryptPIN(arg1:finance.SM2PINRequest):Promise<symmetric.CryptoResult>;

export function SM2Encrypt(arg1:gm.SM2Request):Promise<symmetric.CryptoResult>;

export function SM2EncryptPIN(arg1:finance.SM2PINRequest):Promise<symmetric.CryptoResult>;

export function SM2GenerateKey():Promise<gm.SM2KeyResult>;

export function SM2KeyAgreement(arg1:gm.SM2KeyAgreementRequest):Promise<symmetric.CryptoResult>;

export function SM2Sign(arg1:gm.SM2SignRequest):Promise<symmetric.CryptoResult>;

export function SM2Verify(arg1:gm.SM2VerifyRequest):Promise<symmetric.CryptoResult>;

export function SM3HMAC(arg1:gm.SM3HMACRequest):Promise<symmetric.CryptoResult>;

export function SM3Hash(arg1:gm.SM3Request):Promise<symmetric.CryptoResult>;

export function SM4CMAC(arg1:finance.SM4CMACRequest):Promise<symmetric.CryptoResult>;

export function SM4Decrypt(arg1:gm.SM4Request):Promise<symmetric.CryptoResult>;

export function SM4DecryptFinance(arg1:finance.SM4FinanceRequest):Promise<symmetric.CryptoResult>;

export function SM4DecryptPIN(arg1:finance.SM4PINRequest):Promise<symmetric.CryptoResult>;

export function SM4Encrypt(arg1:gm.SM4Request):Promise<symmetric.CryptoResult>;

export function SM4EncryptFinance(arg1:finance.SM4FinanceRequest):Promise<symmetric.CryptoResult>;

export function SM4EncryptPIN(arg1:finance.SM4PINRequest):Promise<symmetric.CryptoResult>;

export function SM4MAC(arg1:finance.SM4MACRequest):Promise<symmetric.CryptoResult>;

export function SM9Decrypt(arg1:gm.SM9Request):Promise<symmetric.CryptoResult>;

export function SM9Encrypt(arg1:gm.SM9Request):Promise<symmetric.CryptoResult>;

export function SM9GenerateEncKey(arg1:string,arg2:string):Promise<gm.SM9KeyResult>;

export function SM9GenerateMasterKey():Promise<gm.SM9MasterKeyResult>;

export function SM9Sign(arg1:gm.SM9SignRequest):Promise<symmetric.CryptoResult>;

export function SM9Verify(arg1:gm.SM9VerifyRequest):Promise<symmetric.CryptoResult>;

export function SaveFile(arg1:string,arg2:string):Promise<boolean>;

export function SelectFile():Promise<string>;

export function SendPacket(arg1:utils.PacketIORequest):Promise<utils.PacketIOResult>;

export function StringToHex(arg1:string):Promise<utils.ToolResult>;

export function TDESDecrypt(arg1:finance.TDESRequest):Promise<symmetric.CryptoResult>;

export function TDESEncrypt(arg1:finance.TDESRequest):Promise<symmetric.CryptoResult>;

export function TimestampConvert(arg1:utils.TimestampRequest):Promise<utils.ToolResult>;

export function URLDecode(arg1:string):Promise<utils.ToolResult>;

export function URLEncode(arg1:string):Promise<utils.ToolResult>;

export function UnicodeDecode(arg1:string):Promise<utils.ToolResult>;

export function UnicodeEncode(arg1:string):Promise<utils.ToolResult>;

export function VerifyCertChain(arg1:utils.CertChainRequest):Promise<utils.CertChainResult>;

export function X25519Exchange(arg1:asymmetric.X25519Request):Promise<symmetric.CryptoResult>;

export function X25519KeyGen():Promise<asymmetric.KeyPairResult>;

export function XORCompute(arg1:utils.XORRequest):Promise<utils.ToolResult>;

export function ZUCDecrypt(arg1:gm.ZUCRequest):Promise<symmetric.CryptoResult>;

export function ZUCEncrypt(arg1:gm.ZUCRequest):Promise<symmetric.CryptoResult>;
